services:
  postgres:
    image: postgres:16-alpine3.19
    restart: always
    environment:
      - POSTGRES_DB=pgsql-saas
      - POSTGRES_USER=pgsql-saas
      - POSTGRES_PASSWORD=pgsql-saas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  saas-api:
    build:
      context: ./saas
    ports:
      - "8080:8080"
    environment:
      GO_ENV: dev
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./start-and-seed.sh"]

  khairat-api:
    build:
      context: ./api/khairat-api
    ports:
      - "8081:8081"
    environment:
      - GO_ENV=dev
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./khairat-api"]

  tabung-api:
    build:
      context: ./api/tabung-api
    ports:
      - "8082:8082"
    environment:
      - GO_ENV=dev
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./tabung-api"]

  cadangan-api:
    build:
      context: ./api/cadangan-api
    ports:
      - "8083:8083"
    environment:
      - GO_ENV=dev
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./cadangan-api"]

  cadangan-public-api:
    build:
      context: ./api/cadangan-public-api
    ports:
      - "8084:8084"
    environment:
      - GO_ENV=dev
    depends_on:
      - postgres
    command:
      ["./wait-for-it.sh", "saas-api:8080", "--", "./cadangan-public-api"]

  tetapan-api:
    build:
      context: ./api/tetapan-api
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      - GO_ENV=dev
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./tetapan-api"]

  tetapan-public-api:
    build:
      context: ./api/tetapan-public-api
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    environment:
      - GO_ENV=dev
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./tetapan-public-api"]

  dashboard:
    image: dev4w4n/emasjid-dashboard:1aae728195fcfff92e42e2035113419813724f15
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=1aae728195fcfff92e42e2035113419813724f15
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
    ports:
      - "3000:80"
    depends_on:
      - khairat-api
      - tabung-api
      - cadangan-api
      - tetapan-api

  public-web:
    image: dev4w4n/emasjid-public-web:6e79bf4c7c6610773fcc1e8f4b523a2aad35efbb
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=6e79bf4c7c6610773fcc1e8f4b523a2aad35efbb
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
    ports:
      - "3001:80"
    depends_on:
      - cadangan-public-api

  api-docs:
    build:
      context: ./api-docs
    ports:
      - "4000:4000"
    environment:
      - GO_ENV=dev
    depends_on:
      - tabung-api
      - cadangan-api
      - cadangan-public-api
      - khairat-api
      - tetapan-api
      - tetapan-public-api

volumes:
  postgres_data:
