services:
  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres/901_zz_tetapan_types.sql:/docker-entrypoint-initdb.d/901_zz_tetapan_types.sql:ro
      - ./postgres/902_zz_dummy.sql:/docker-entrypoint-initdb.d/902_zz_dummy.sql:ro

  khairat-api:
    build:
      context: ./api/khairat-api
    ports:
      - "8081:8081"
    environment:
      - GO_ENV=dev
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./khairat-api"]

  tabung-api:
    build:
      context: ./api/tabung-api
    ports:
      - "8082:8082"
    environment:
      - GO_ENV=dev
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./tabung-api"]

  cadangan-api:
    build:
      context: ./api/cadangan-api
    ports:
      - "8083:8083"
    environment:
      - GO_ENV=dev
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./cadangan-api"]

  cadangan-public-api:
    build:
      context: ./api/cadangan-public-api
    ports:
      - "8084:8084"
    environment:
      - GO_ENV=dev
    depends_on:
      - postgres
    command:
      ["./wait-for-it.sh", "postgres:5432", "--", "./cadangan-public-api"]

  tetapan-api:
    build:
      context: ./api/tetapan-api
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      - GO_ENV=dev
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./tetapan-api"]

  tetapan-public-api:
    build:
      context: ./api/tetapan-public-api
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    environment:
      - GO_ENV=dev
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./tetapan-public-api"]

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - khairat-api
      - tabung-api
      - cadangan-api
      - tetapan-api

  public-web:
    build:
      context: ./public-web
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    depends_on:
      - cadangan-public-api

  api-docs:
    build:
      context: ./api-docs
    ports:
      - "4000:4000"
    environment:
      - GO_ENV=dev
    depends_on:
      - tabung-api
      - cadangan-api
      - cadangan-public-api
      - khairat-api
      - tetapan-api
      - tetapan-public-api
