apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.global.env }}-{{ .Values.global.tenant }}-db-secret"
  namespace: "{{ .Values.global.env }}-{{ .Values.global.tenant }}"
  labels:
    tenant: {{ .Values.global.tenant | quote }}
    env: {{ .Values.global.env | quote }}
type: Opaque
data:
  DB_USER: {{ .Values.global.db.user | b64enc }}
  DB_PASSWORD: {{ .Values.global.db.password | b64enc }}
