apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-frontend-ingress
  namespace: "{{ .Values.global.env }}-{{ .Values.global.tenant }}"
  labels:
    tenant: {{ .Values.global.tenant }}
    env: {{ .Values.global.env | quote }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.global.tenant }}.e-masjid.my"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: public-web-service
            port:
              number: 80


