apiVersion: v1
kind: Service
metadata:
  name: public-web-service
  labels:
    app: public-web
    tenant: {{ .Values.global.tenant }}
spec:
  selector:
    app: public-web
    tenant: {{ .Values.global.tenant }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.services.publicWeb.port }}
      targetPort: {{ .Values.services.publicWeb.targetPort }}
      nodePort: {{ .Values.services.publicWeb.nodePort }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-web
  labels:
    app: public-web
    tenant: {{ .Values.global.tenant }}
spec:
  selector:
    matchLabels:
      app: public-web
      tenant: {{ .Values.global.tenant }}
  replicas: 1
  template:
    metadata:
      labels:
        app: public-web
        tenant: {{ .Values.global.tenant }}
    spec:
      containers:
        - name: public-web
          image: {{ .Values.services.publicWeb.image }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "500m"   
          env:
            - name: EMASJID_REACT_APP_BUILD_VERSION
              value: "v2.3.1"
            - name: EMASJID_REACT_APP_DOMAIN
              value: "e-masjid.my"
            - name: GO_ENV
              value: "local"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: {{ .Values.services.publicWeb.containerPort }}