apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv 
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-storage
  local:
    path: /mnt/disks/minikube-data  # Path to your local storage directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: default/disk
              operator: In
              values:
                - ssd  # Ensure the PV is tied to the correct node