apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-api
  labels:
    app: saas-api
spec:
  selector:
    matchLabels:
      app: saas-api
  replicas: 1
  template:
    metadata:
      labels:
        app: saas-api
    spec:
      containers:
        - name: saas-api
          image: dev4w4n/emasjid-saas:v2.3.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m" 
          env:
            - name: EMASJID_REACT_APP_BUILD_VERSION
              value: "v2.3.1"
            - name: EMASJID_REACT_APP_DOMAIN
              value: "e-masjid.my"
            - name: GO_ENV
              value: "docker"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "pgsql-saas"
            - name: DB_PASSWORD
              value: "pgsql-saas"
            - name: DB_NAME
              value: "pgsql-saas"
          ports:
            - containerPort: 8080
          args: ["./wait-for-it.sh", "postgres:5432", "--", "./start-and-seed.sh"]