name: Publish to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "public-web/**"

jobs:
  build-public-web:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and publish to Docker Hub
        run: |
          VERSION=$(git rev-parse HEAD)  # Use short commit hash for versioning
          IMAGE_NAME=dev4w4n/emasjid-public-web:${VERSION}
          docker build -t emasjid-public-web --build-arg BUILD_VERSION=${VERSION} --build-arg DOMAIN=e-masjid.my ./public-web
          docker tag emasjid-public-web $IMAGE_NAME
          docker push $IMAGE_NAME
